### ISSUE TITLE
dotaz

### ISSUE THREAD

**Issue by horiee** [JirkaZelenka/Sreality#4]
https://github.com/JirkaZelenka/Sreality/blob/96e805c7437ac68e0dcca5132aaaaa69556b2ef5/config.py#L29

Dobry den, diky za kod, usetri mi to dost casu na mem projektu :-) chci se zeptat mate nekde dim taxonomy na jednotive kategorie? vsiml jsem si, ze v output payloadu z API leze k/v **seo**, v kterem je category_main_cb, category_sub_cb, category_type_cb a locality, podle ktereho se da slozit url na landing page sreality.cz pro dany inzerat.
Dekuji

**Comment by JirkaZelenka** [comment]
Dobrý den, neívm teď přesně, jak by mělo vypadat dim taxonomy, nicméně ty detaily pro category_main_cb atd. jsem čerpal z této  práce (kapitola 3).
https://dspace.cvut.cz/bitstream/handle/10467/103384/F8-BP-2021-Malach-Ondrej-thesis.pdf?sequence=-1&isAllowed=y

Až si projdu víc ta data, tak možná připravím nějaký lepší mapping  všech těch číselných parametrů na textové hodnoty, pokud jde o tohle:)

**Comment by horiee** [comment]
Diky, presne to jsem mel na mysli :-)
